INSERT INTO gen2brand(generic, brand_name) VALUES ('Abaraterone','Zytiga');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Alemtuzumab','Campath');
INSERT INTO gen2brand(generic, brand_name) VALUES ('All-trans-retinoic acid','ATRA, tretinoin');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Altretamine','Hexalen');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Amifostine','Ethyol');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Aminoglutethimide','Cytadren');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Amsacrine','Amsidine');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Anastrozole','Arimidex');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Arsenic trioxide','As2O3, Trisenox');
INSERT INTO gen2brand(generic, brand_name) VALUES ('L-Asparaginase','Elspar');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Azacitidine','Vidaza');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Bendamustine','Treanda');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Bevacizumab','Avastin');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Bexarotene','Targretin');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Bicalutamide','Casodex');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Bleomycin','Blenoxane');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Bortezomib','Velcade');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Brentuximab vedotin','Adcetris');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Buserelin','Suprefact');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Busulfan','Myleran');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Cabazitaxel','Jevtana');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Capecitabine','Xeloda');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Carfilzomib','Kyprolis');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Carboplatin','Paraplatin');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Carmustine','BCNU');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Cetuximab','Erbitux');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Chlorambucil','Leukeran');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Cimetidine','Tagamet, various');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Cisplatin','CDDP');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Cladribine','2-CdA');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Crizotinib','Xalkori');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Cyclophosphamide','Cytoxan');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Cytarabine','Ara-C');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Dacarbazine','DTIC');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Dactinomycin','Actinomycin');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Dasatinib','Sprycel');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Daunorubicin (various)','various');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Daunorubicin (liposomal)','DaunoXome');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Degarelix','Firmagon');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Denileukin diftitox','Ontak');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Dexamethasone','various');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Diphenhydramine','Benadryl Injection, various');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Docetaxel','Taxotere');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Doxorubicin','Adriamycin, various');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Doxorubicin (Pegylated liposomal doxorubicin)','Doxil, various');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Enzalutamide','Xtandi');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Epirubicin','Ellence, various');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Eribulin','Halaven');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Erlotinib','Tarceva');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Estramustine','Estracyte');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Etoposide','VP-16');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Everolimus','Afinitor, Zortress');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Exemestane','Aromasin, various');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Filgrastim(G-CSF)','Neupogen');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Floxuridine','FUDR');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Fludarabine','Fludara');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Fluorouracil','5-FU');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Flutamide','various');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Fulvestrant','Faslodex');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Gemcitabine','Gemzar, various');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Goserelin','Zoladex');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Hydrocortisone','various');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Hydroxyurea','Hydrea');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Ibritumomab tiuxetan','Zevalin');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Idarubicin','Idamycin');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Ifosfamide','Ifex');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Imatinib','Gleevec');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Interferon –alpha-2a','Roferon-A');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Interferon –alpha-2','Intron-A');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Interferon –alpha-2b(Pegilated)','Sylatron');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Interleukin-2(aldesleukin)','Proleukin');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Ipilimumab','Yervoy');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Irinotecan  ','Camptosar, CPT-11');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Ixabepilone','Ixempra');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Lapatinib','Tykerb');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Lenalidomide','Revlimid');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Letrozole','Femara');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Leucovorin calcium(LV)','various');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Leuprolide acetate','Lupron');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Leuprolide acetate depot','Lupron depot');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Lomustine','CCNU');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Mechlorethamine (Nitrogen mustard)','Mustargen');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Medroxyprogesterone acetate','Provera, various');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Megestrol acetate','Megace');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Melphalan','Alkeran');
INSERT INTO gen2brand(generic, brand_name) VALUES ('6-Mercaptopurine','6-MP');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Mesna','Mesnex, various');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Methotrexate (MTX)','MTX LPF, MTX sodium, MTX sodium preservative free, various');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Methylprednisolone','Depo-Medrol, Solu-Medrol, various');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Mitomycin-C','Mutamycin');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Mitoxantrone','Novantrone');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Nilotinib','Tasigna');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Nilutamide','Nilandron');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Ofatumumab','Arzerra');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Oxaliplatin','Eloxatin, Oxaliplatin, various');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Paclitaxel','Taxol');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Paclitaxel protien-bound particles','Abraxane');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Pazopanib','Votrient');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Pegasparaginase','Oncaspar');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Pemetrexed','Alimta');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Pentostatin','Nipent');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Pralatrexate','Folotyn');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Prednisolone','Flo-pred, various');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Prednisone','various');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Procarbazine','Matulane');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Ranitidine','Zantac, various');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Regorafenib','Stivarga');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Rituximab','Rituxan');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Sipuleucel-T','Provenge');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Sorafenib','Nexavar');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Streptozocin','Zanosar');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Sunitinib','Sutent');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Tamoxifen','Nolvadex');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Temozolomide','Temodar');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Temsirolimus  ','Torisel');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Thalidomide','Thalomid');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Thioguanine','6-TG');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Topotecan','Hycamtin');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Toremifene citrate','Fareston');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Tositumomab+ I-131 tositumomab','Bexxar');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Trastuzumab','Herceptin');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Triptorelin pamoate depot','Trelstar Depot');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Vemurafenib','Zelboraf');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Vinblastine','Velban');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Vincristine','Oncovin, VCR');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Vinorelbine','Navelbine');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Vorinostat','Zolinza');
INSERT INTO gen2brand(generic, brand_name) VALUES ('Pomalidamide','Pomalyst');
insert into gen2brand(generic, brand_name) values ('Obinutuzumab','Gazyva');
insert into gen2brand(generic, brand_name) values ('Ibrutinib','Imbruvica');	
insert into gen2brand(generic, brand_name) values ('Ofatumumab','Arzerra');
insert into gen2brand(generic, brand_name) values ('Blinatumomab','Blincyto');
insert into gen2brand(generic, brand_name) values ('Ixazomib','Ninlaro');
insert into gen2brand(generic, brand_name) values ('Daratumumab','Darzalex');
insert into gen2brand(generic, brand_name) values ('Nivolumab','Opdivo');
insert into gen2brand(generic, brand_name) values ('Axitinib','Inlyta');
insert into gen2brand(generic, brand_name) values ('Vemurafinib','Zelboraf');
insert into gen2brand(generic, brand_name) values ('Ipilumimab','Yervoy');
insert into gen2brand(generic, brand_name) values ('Dabrafenib','Tafinlar');
insert into gen2brand(generic, brand_name) values ('Trametinib','Mekinist');
insert into gen2brand(generic, brand_name) values ('Cobimetinib','Cotellic');
insert into gen2brand(generic, brand_name) values ('Pembrolizumab','Keytruda');
insert into gen2brand(generic, brand_name) values ('Trifluridine/Tiparcil','Lonsurf');
insert into gen2brand(generic, brand_name) values ('Elotuzumab','Empliciti');
insert into gen2brand(generic, brand_name) values ('Ramucirumab','Cyramza');
insert into gen2brand(generic, brand_name) values ('Nab-Paclitaxel','Abraxane');
insert into gen2brand(generic, brand_name) values ('Irinotecan liposome','Onivyde');
insert into gen2brand(generic, brand_name) values ('Everolimus','Afinitor');
insert into gen2brand(generic, brand_name) values ('Idelalisib','Zydellig');
insert into gen2brand(generic, brand_name) values ('Pertuzumab','Perjeta');
insert into gen2brand(generic, brand_name) values ('Ado-trastuzumab','Kadcyla');
insert into gen2brand(generic, brand_name) values ('Ceritinib','Zykadia');
insert into gen2brand(generic, brand_name) values ('Necitumumab','Portrazza');
insert into gen2brand(generic, brand_name) values ('Osimertinib','Tagrisso');
insert into gen2brand(generic, brand_name) values ('Afatinib','Gilotrif');
insert into gen2brand(generic, brand_name) values ('Gefitinib','Iressa');
insert into gen2brand(generic, brand_name) values ('Belinostat','Beleodaq');
insert into gen2brand(generic, brand_name) values ('Brentuximabvedotin','Adcetris');